### ISSUE TITLE
Þarf að geta gefið staðsetningu gagnagrunns í FlightController

### ISSUE THREAD

**Issue by KjartanOli** [ofurtumi/flight-booking#49]
Við í T þurfum að geta gefið staðsetningu gagnagrunnsins sem FlightController sækir í, á sama hátt og BookingController í Pr #47

**Comment by ofurtumi** [comment]
Addressað í PR #48 sjá https://github.com/ofurtumi/flight-booking/commit/7a86e215e4149241d5613f84f6560a9ecb0f26c4
